# name: Doploy A Web Application on EC2 Instance Using Github Actions

# on:
#   push:
#     branches: [ "main" ]

# job:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Checkout Source
#         uses: actions/checkout@v3
#       - name: Login to Docker Hub
#         uses: login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Docker Image
#         run: docker build -t wisdomtech/wisdomweb . 
#       - name: Push image to docker Hub
#       - run: docker push wisdomtech/wisdomweb:latest

#   deploy:
#     needs: build
#     runs-on: aws-ec2 #aws-ec2 is a selfhosted runners
#     steps:
#       - name: Pull the image from Docker Hub 
#         run: docker pull wisdomtech/wwisdomweb:latest 
#       - name: Delete Old Container if it exists
#       - run: docker rm -f wisdomcontainer
#       - name: Run The Docker container
#         run: docker run -d --name wisdomtechapp -p 8900:80 wisdomtech/wisdomweb

name: Doploy A Web Application on EC2 Instance Using Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build aand Push Docker image to Docker Hub
      run: |
        IMAGE_TAG=latest
        sudo docker build -t wisdomtech/wisdomweb:$IMAGE_TAG .
        sudo docker push wisdomtech/wisdomweb:$IMAGE_TAG 

  deploy:
    needs: build
    runs-on: aws-ec2 #aws-ec2 is a selfhosted runners
    steps:
    - name: Pull the image from Docker Hub 
      run: docker pull wisdomtech/wwisdomweb:latest 
    - name: Delete Old Container if it exists
      run: docker rm -f wisdomcontainer

    - name: Run The Docker container
      run: docker run -d --name wisdomtechapp -p 8900:80 wisdomtech/wisdomweb
        



  

