name: Doploy A Web Application on EC2 Instance Using Github Action

on:
  push:
    branches: [ "main" ]

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: login -u ${{ secrets.DOCKER_USERNAME }} -P ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t wisdomtech/wwisdomweb . 
      - name: Push image to docker Hub
      - run: docker push wisdomtech/wwisdomweb:latest

  deploy:
    needs: build
    runs-on: aws-ec2 #aws-ec2 is a selfhosted runners
    steps:
      - name: Pull the image from Docker Hub 
        run: docker pull wisdomtech/wwisdomweb:latest 
      - name: Delete Old Container if it exists
      - run: docker rm -f wisdomcontainer
      - name: Run The Docker container
        run: docker run -d --name wisdomtechapp -p 8900:80 wisdomtech/wwisdomweb
  

